camunda/bpmnlint-plugin-camunda-compat

- rules/camunda-cloud-1-0.js
- rules/camunda-cloud-1-1.js
- rules/camunda-cloud-1-2.js
- rules/camunda-cloud-1-3.js
- rules/camunda-cloud-8-0.js
- rules/utils/rule.js
- test/camunda-cloud/camunda-cloud-1-0.spec.js
- test/camunda-cloud/camunda-cloud-1-1.spec.js
- test/camunda-cloud/camunda-cloud-1-2.spec.js
- test/camunda-cloud/camunda-cloud-1-3.spec.js
- test/camunda-cloud/camunda-cloud-8-0.spec.js
- test/camunda-cloud/integration/camunda-cloud-1-0/camunda-cloud-1-0-integration.spec.js
- test/camunda-cloud/integration/camunda-cloud-1-1/camunda-cloud-1-1-integration.spec.js
- test/camunda-cloud/integration/camunda-cloud-1-2/camunda-cloud-1-2-integration.spec.js
- test/camunda-cloud/integration/camunda-cloud-1-3/camunda-cloud-1-3-integration.spec.js
Related to https://github.com/bpmn-io/internal-docs/issues/481
> Rename Cloud to Platform/Zeebe

- CHANGELOG.md
Updated changelog for already released version v0.3.0 (which was missing) and upcoming v0.4.0
> chore(CHANGELOG): update to v0.4.0

- CHANGELOG.md
Getting ready for the release. 🚀
> chore(CHANGELOG): update to v0.5.0

- docs/ERRORS.md
- rules/camunda-cloud-1-0-checks.js
- rules/camunda-cloud-1-0.js
- rules/camunda-cloud-1-1-checks.js
- rules/camunda-cloud-1-1.js
- rules/camunda-cloud-1-2-checks.js
- rules/camunda-cloud-1-2.js
- rules/camunda-cloud-1-3-checks.js
- rules/camunda-cloud-1-3.js
- rules/camunda-cloud-8-0.js
- rules/utils/element.js
- rules/utils/rule.js
- rules/utils/type.js
- test/camunda-cloud/camunda-cloud-1-0.spec.js
- test/camunda-cloud/camunda-cloud-1-1.spec.js
- test/camunda-cloud/camunda-cloud-1-2.spec.js
- test/camunda-cloud/camunda-cloud-1-3.spec.js
- test/utils/cloud/element.spec.js
- test/utils/element.spec.js
- test/utils/rule.spec.js
- test/utils/type.spec.js
> Friendly Error Messages

- CHANGELOG.md
* `FEAT`: adjust error messages to be more friendly ([#22](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/22))
* `FEAT`: lint error code and message name ([#21](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/21))
* `FIX`: task definition retries not required ([#20](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/20))
> chore(CHANGELOG): update to v0.6.0

- rules/camunda-cloud-1-3-checks.js
- test/camunda-cloud/camunda-cloud-1-3.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/2927. This is half of the fix. The other half is in the Camunda Modeler (cf. https://github.com/camunda/camunda-modeler/pull/2933). I'll release a patch version and include that in the Camunda Modeler fix.
> fix: fix error message formatting

- CHANGELOG.md
- README.md
* adjust README to reflect new plugin structure
* update CHANGELOG
> Prepare 0.8.0

- CHANGELOG.md
* `FIX`: ignore null properties ([#39](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/39))
> chore(CHANGELOG): update to 0.9.2

- rules/element-type/config.js
- test/camunda-cloud/camunda-cloud-8-1-element-type.spec.js
- test/camunda-cloud/integration/camunda-cloud-8-1-valid.bpmn
related to https://github.com/camunda/camunda-modeler/issues/3149
> feat(rules): support terminate end event in 8.1

- index.js
- rules/element-type/config.js
- test/camunda-cloud/camunda-cloud-1-0-element-type.spec.js
- test/camunda-cloud/camunda-cloud-1-1-element-type.spec.js
- test/camunda-cloud/camunda-cloud-1-2-element-type.spec.js
- test/camunda-cloud/camunda-cloud-8-0-element-type.spec.js
- test/camunda-cloud/camunda-cloud-8-2-element-type.spec.js
- test/camunda-cloud/integration/called-decision-or-task-definition.spec.js
- test/camunda-cloud/integration/called-element.spec.js
- test/camunda-cloud/integration/camunda-cloud-8-0-element-type.bpmn
- test/camunda-cloud/integration/camunda-cloud-8-2-called-decision-or-task-definition-errors.bpmn
- test/camunda-cloud/integration/camunda-cloud-8-2-called-decision-or-task-definition.bpmn
- test/camunda-cloud/integration/camunda-cloud-8-2-element-type-errors.bpmn
- test/camunda-cloud/integration/camunda-cloud-8-2-element-type.bpmn
- test/camunda-cloud/integration/camunda-cloud-8-2-timer-errors.bpmn
- test/camunda-cloud/integration/camunda-cloud-8-2-timer.bpmn
- test/camunda-cloud/integration/duplicate-task-headers.spec.js
- test/camunda-cloud/integration/element-type.spec.js
- test/camunda-cloud/integration/error-reference.spec.js
- test/camunda-cloud/integration/executable-process.spec.js
- test/camunda-cloud/integration/feel.spec.js
- test/camunda-cloud/integration/inclusive-gateway.spec.js
- test/camunda-cloud/integration/loop-characteristics.spec.js
- test/camunda-cloud/integration/message-reference.spec.js
- test/camunda-cloud/integration/subscription.spec.js
- test/camunda-cloud/integration/timer.spec.js
- test/camunda-cloud/integration/user-task-form.spec.js
- test/config/configs.spec.js
- Undefined Task (related to https://github.com/camunda/camunda-modeler/issues/3230)
- DataStore/DataObject (https://github.com/camunda/camunda-modeler/issues/3277)
> feat: add 8.2 config and supported elements

- rules/utils/iso8601.js
- test/utils/iso8601.spec.js
> fix: support weeks in duration

- rules/no-expression.js
- test/camunda-cloud/no-expression.spec.js
> fix: apply no-expression#errorCode to throw events only

- CHANGELOG.md
- package-lock.json
- rules/element-type/config.js
- rules/no-expression.js
- test/camunda-cloud/camunda-cloud-8-2-element-type.spec.js
- test/camunda-cloud/integration/camunda-cloud-8-2-element-type.bpmn
- test/camunda-cloud/no-expression.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3318
> feat: allow escalation events in Camunda 8.2

- index.js
- rules/escalation-reference.js
- test/camunda-cloud/escalation-reference.spec.js
- test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3318
> feat: require escalation and escalation code in Camunda 8.2

- rules/sequence-flow-condition.js
- test/camunda-cloud/integration/sequence-flow-condition-errors.bpmn
- test/camunda-cloud/integration/sequence-flow-condition.bpmn
- test/camunda-cloud/integration/sequence-flow-condition.spec.js
- test/camunda-cloud/sequence-flow-condition.spec.js
> feat: allow conditional flow only if source is (in/ex)clusive gateway

- index.js
- test/camunda-platform/integration/history-time-to-live.spec.js
- test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3632
> feat(platform): add platform 7.20 rules

- CHANGELOG.md
- package-lock.json
- package.json
Follow-up to https://github.com/bpmn-io/bpmnlint/pull/110.
> deps: update bpmnlint to v9.0.0

- rules/utils/iso8601.js
- test/utils/iso8601.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3709
> fix(timer): allow repeating interval start

- CHANGELOG.md
- index.js
- test/config/configs.spec.js
Required by https://github.com/camunda/linting/pull/67.
> feat: add `all` config

- CHANGELOG.md
- index.js
- rules/camunda-cloud/start-form.js
- test/camunda-cloud/start-form.spec.js
- test/config/configs.spec.js
closes #106
integration PR will adjust error message: https://github.com/camunda/linting/pull/75
> feat(cloud): add start form rule

- .github/ISSUE_TEMPLATE/BUG_REPORT
Without this people can only propose new rules :see_no_evil:.
> chore: add BUG_REPORT template

- package-lock.json
- package.json
- rules/camunda-cloud/no-propagate-all-parent-variables.js
- test/camunda-cloud/integration/no-propagate-all-parent-variables-errors.bpmn
- test/camunda-cloud/integration/no-propagate-all-parent-variables.bpmn
- test/camunda-cloud/no-propagate-all-parent-variables.spec.js
> fix: only value `false` is not allowed

- CHANGELOG.md
- package-lock.json
- package.json
related to https://github.com/camunda/camunda-modeler/issues/3806
> deps: update to @bpmn-io/feel-lint@1.0.0

- rules/camunda-cloud/no-loop.js
- rules/camunda-cloud/user-task-form.js
- rules/utils/element.js
- test/camunda-cloud/no-loop.spec.js
Follow-up to https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/102
Related to #100
> feat: detect call activity loops

- index.js
- rules/camunda-cloud/element-type/config.js
- rules/camunda-cloud/no-signal-event-sub-process.js
- test/camunda-cloud/camunda-cloud-8-3-element-type.spec.js
- test/camunda-cloud/no-signal-event-sub-process.spec.js
- test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3819
> Allow signal boundary events, signal catch events, signal start events in subprocess

- rules/camunda-cloud/signal-reference.js
- test/camunda-cloud/signal-reference.spec.js
Related to https://github.com/camunda/camunda-modeler/pull/3885#issuecomment-1734977272
> fix(signal): intermediate catch has signal reference

- package.json
- rules/camunda-cloud/element-type/index.js
- rules/camunda-cloud/implementation/index.js
- rules/camunda-cloud/no-expression.js
- rules/utils/element.js
- test/camunda-cloud/camunda-cloud-1-0-element-type.spec.js
- test/camunda-cloud/camunda-cloud-1-1-element-type.spec.js
- test/camunda-cloud/camunda-cloud-1-2-element-type.spec.js
- test/camunda-cloud/camunda-cloud-8-0-element-type.spec.js
- test/camunda-cloud/camunda-cloud-8-1-element-type.spec.js
- test/camunda-cloud/camunda-cloud-8-2-element-type.spec.js
- test/camunda-cloud/error-reference.spec.js
- test/camunda-cloud/implementation.spec.js
- test/camunda-cloud/no-candidate-users.spec.js
- test/camunda-cloud/no-expression.spec.js
- test/camunda-cloud/no-propagate-all-parent-variables.spec.js
- test/camunda-cloud/no-task-schedule.spec.js
- test/camunda-cloud/no-template.spec.js
- test/camunda-cloud/no-zeebe-properties.spec.js
- test/camunda-cloud/start-form.spec.js
- test/camunda-cloud/timer.spec.js
- test/utils/element.spec.js
> Rename `Camunda Platform` to `Camunda`

- index.js
- test/config/configs.spec.js
related to https://github.com/camunda/camunda-modeler/issues/3921
> feat(config): add 8.4 config

- index.js
- rules/camunda-cloud/user-task-form.js
- test/camunda-cloud/user-task-form.spec.js
> Validate `formId` Introduced by Camunda 8.3

- index.js
- rules/camunda-cloud/collapsed-subprocess.js
- test/camunda-cloud/collapsed-subprocess.spec.js
- test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/4020
> feat: allow collapsed subprocess in 8.4

- CHANGELOG.md
- rules/camunda-cloud/user-task-form.js
- test/camunda-cloud/user-task-form.spec.js
Related to https://github.com/camunda/product-hub/issues/1917#issuecomment-1896695270
> feat(user-task-form): ensure form

- index.js
- rules/camunda-cloud/user-task-definition.js
- rules/camunda-cloud/user-task-form.js
- test/camunda-cloud/integration/secrets.spec.js
- test/camunda-cloud/integration/user-task-definition-errors.bpmn
- test/camunda-cloud/integration/user-task-definition.bpmn
- test/camunda-cloud/integration/user-task-definition.spec.js
- test/camunda-cloud/user-task-definition.spec.js
- test/camunda-cloud/user-task-form.spec.js
- test/config/configs.spec.js
> Report Warning Instead of Error if No Form Definition

- rules/camunda-cloud/escalation-reference.js
- test/camunda-cloud/escalation-reference.spec.js
- test/camunda-cloud/integration/escalation-reference-errors.bpmn
- test/camunda-cloud/integration/escalation-reference.bpmn
- test/camunda-cloud/integration/escalation-reference.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/4064
> fix(escalation-reference): allow start event without escalation ref

- index.js
- rules/camunda-platform/history-time-to-live.js
- test/camunda-platform/history-time-to-live.spec.js
- test/camunda-platform/integration/history-time-to-live.spec.js
- test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/4062
> feat(platform): report informative message on HTTP missing

- index.js
- rules/camunda-cloud/element-type/config.js
- rules/camunda-cloud/wait-for-completion.js
- test/camunda-cloud/integration/camunda-cloud-8-5-element-type-errors.bpmn
- test/camunda-cloud/integration/camunda-cloud-8-5-element-type.bpmn
- test/camunda-cloud/integration/element-type.spec.js
- test/camunda-cloud/wait-for-completion.spec.js
- test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3945
> Add compensation support

- CHANGELOG.md
- index.js
- test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3613
> feat: allow converging inclusive gateway in 8.6

- index.js
- test/config/configs.spec.js
- camunda cloud v8.7
- camunda platform v7.23
related to https://github.com/camunda/camunda-modeler/issues/4610
> feat: add new alpha versions

- .github/workflows/CI.yml
Ensure we use latest GitHub actions, CI will otherwise [start to fail sporadically](https://github.com/camunda/bpmnlint-plugin-camunda-compat/actions/runs/13396003229/job/37415084406) :).
> Updates to latest `actions/*`

- eslint.config.mjs
- package-lock.json
- package.json
Follow up to https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/188#discussion_r1959540810, this ensures we expose environment agnostic rules and implementation.
> chore: ensure we build rules in environment agnostic fashion

- index.js
- test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/4984
add new 7.24 linting profile
> feat: add 7.24 profile

- CHANGELOG.md
- package-lock.json
- package.json
* bump bpmnlint to v11.6.0
* update CHANGELOG to v2.26.0
> Bump bpmnlint

- rules/camunda-cloud/feel.js
- test/camunda-cloud/feel.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/4809
Set Feel Parser Dialect to camunda
> feat: use feelParserDialect `camunda`

- rules/camunda-cloud/feel.js
- test/camunda-cloud/feel.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/5203
Adding new context entries leads to performance issues across the stack. This PR reverts the inclusion of camunda feel builtins until we can handle increased context sizes more performantly. 
> Revert inclusion of camunda feel builtins
