rules/utils/cloud/element.js, rules/utils/element.js, test/camunda-cloud/camunda-cloud-1-0.spec.js, test/camunda-cloud/camunda-cloud-1-1.spec.js, test/camunda-cloud/camunda-cloud-1-2.spec.js, test/utils/cloud/element.spec.js, test/utils/element.spec.js
`zeebe:retries` property of `zeebe:TaskDefinition` extension elements isn't required.
---
Related to https://github.com/camunda/camunda-modeler/pull/2861#issuecomment-1084430700
=> fix: remove task definition retries check

rules/camunda-cloud-1-0-checks.js, rules/utils/element.js, test/camunda-cloud/camunda-cloud-1-0.spec.js, test/utils/element.spec.js
* `<bpmn:errorCode`> of <bpmn:Error> is required
* `<bpmn:name`> of <bpmn:Message> is required
---
Related to https://github.com/camunda/camunda-modeler/pull/2861#issuecomment-1084457168
=> Check errors and messages

rules/camunda-cloud-1-0-checks.js, rules/utils/element.js, test/camunda-cloud/camunda-cloud-1-0.spec.js, test/utils/element.spec.js
Lanes are actually supported by Zeebe. The engine will not throw an error when deploying a BPMN with lanes.
=> fix: remove lanes check

CHANGELOG.md
* `FEAT`: refactor plugin structure ([#29](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/29))
* `DEPS`: update to `bpmnlint@7.8.0` ([#29](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/29))
* configuration not selected based on execution platform and version anymore
* error message not adjusted to be shown in Camunda Modeler anymore
* error type ELEMENT_TYPE changed to ELEMENT_TYPE_NOT_ALLOWED
* error type PROPERTY_TYPE changed to PROPERTY_TYPE_NOT_ALLOWED
* error data changed (cf. docs/ERRORS.md)
=> chore(CHANGELOG): update to v0.7.0

rules/has-subscription.js, test/camunda-cloud/has-subscription.spec.js
Message start events only need a `zeebe:Subscription` extension element with a `zeebe:correlationKey` property if they are children of an event sub process. The Zeebe engine validates that correctly (cf. https://github.com/camunda/zeebe/blob/1.3.0/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/MessageValidator.java#L49).
---
Related to https://github.com/camunda/camunda-modeler/issues/2983
=> fix: lint subscription only if start event child of sub process

index.js, rules/user-task-form.js, rules/utils/element.js, test/camunda-cloud/integration/camunda-cloud-1-0-invalid.bpmn, test/camunda-cloud/integration/camunda-cloud-1-0-valid.bpmn, test/camunda-cloud/integration/camunda-cloud-1-0.spec.js, test/camunda-cloud/integration/camunda-cloud-1-1-invalid.bpmn, test/camunda-cloud/integration/camunda-cloud-1-1.spec.js, test/camunda-cloud/integration/camunda-cloud-1-2-invalid.bpmn, test/camunda-cloud/integration/camunda-cloud-1-2.spec.js, test/camunda-cloud/integration/camunda-cloud-1-3-invalid.bpmn, test/camunda-cloud/integration/camunda-cloud-1-3.spec.js, test/camunda-cloud/integration/camunda-cloud-8-0-invalid.bpmn, test/camunda-cloud/integration/camunda-cloud-8-0.spec.js, test/camunda-cloud/user-task-form.spec.js, test/configs.spec.js
This rule ensures that
* `zeebe:FormDefinition` elements have a `zeebe:formKey` property
* `zeebe:UserTaskForm` elements are not empty
---
Related to https://github.com/bpmn-io/internal-docs/issues/532
=> Add User Task Forms Rule

rules/utils/reporter.js, test/utils/reporter.spec.js
Adding the name of the node was accidentally removed in https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/29. It will be displayed in the Camunda Modeler Error Panel.
=> fix: add name (again)

rules/utils/element.js, test/helper.js, test/utils/element.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3067
=> fix: ignore null properties

docs/ERRORS.md, index.js, rules/duplicate-task-headers.js, rules/user-task-form.js, rules/utils/element.js, rules/utils/error-types.js, test/camunda-cloud/duplicate-task-headers.spec.js, test/configs.spec.js, test/utils/element.spec.js
Related to https://github.com/camunda/linting/issues/4
Adds the `duplicate-task-headers` rule to check for duplicate `zeebe:Header` elements (by key).
=> feat(rules): add `duplicate-task-headers` rule

index.js, rules/collapsed-subprocess.js, rules/utils/error-types.js, test/camunda-cloud/collapsed-subprocess.spec.js, test/config/configs.spec.js
This PR adds lint rules to support modeling of all elements in Camunda 8.x. ~~It also adds the none-task to the list of supported elements.~~
Undefined Task will be handled in a separate PR
Because we have a whitelist of supported elements, we only need to add collapsed subprocesses as unsupported.
downstream PR: https://github.com/camunda/linting/pull/33
closes https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/46
=> Camunda 8 modeling only

CHANGELOG.md
* `FEAT`: add `feel` rule to validate feel expressions ([#51](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/51))
* `FEAT`: add `collapsed-subprocess` rule to disallow collapsed subprocess ([#52](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/52))
* `CHORE`: `element-type` rule handles all errors using `ELEMENT_TYPE_NOT_ALLOWED` error type ([#50](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/50))
* `CHORE`: `timer` rule handles `bpmn:FormalExpression` elements using new error types `EXPRESSION_REQUIRED` and `EXPRESSION_VALUE_NOT_ALLOWED` ([#50](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/50))
* `CHORE`: refactor configuration of rules ([#50](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/50))
* rules that …
=> chore(CHANGELOG): update to v0.14.0

CHANGELOG.md, rules/collapsed-subprocess.js, rules/feel.js, test/camunda-cloud/collapsed-subprocess.spec.js, test/camunda-cloud/feel.spec.js
...also fixes a typo in the FEEL message, while we're at it.
=> fix(subprocess): lint element without `isExpanded`

index.js, rules/inclusive-gateway.js, rules/sequence-flow-condition.js, test/camunda-cloud/inclusive-gateway.spec.js, test/camunda-cloud/sequence-flow-condition.spec.js, test/config/configs.spec.js
Conditions now checked for both exclusive and inclusive gateways.
* separate `inclusive-gateway` into 2 parts
* `inclusive-gateway` rule checks number of incoming sequence flows of inclusive gateway
* `sequence-flow-condition` rule checks condition of outgoing sequence flows of exclusive and inclusive gateway
=> feat: add `sequence-flow-condition` rule

CHANGELOG.md
* `FEAT`: add `executable-process` rule ([#56](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/56))
* `FEAT`: add `sequence-flow-condition` rule ([#58](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/58))
* `FEAT`: add Camunda Platform 8.2 config ([#59](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/59))
* `FEAT`: add elements supported by Camunda Platform 8.2 to `element-type` rule ([#59](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/59))
=> chore(CHANGELOG): update to v0.15.0

rules/called-decision-or-task-definition/config.js, rules/called-decision-or-task-definition/index.js, rules/element-type/config.js, test/camunda-cloud/called-decision-or-task-definition.spec.js, test/camunda-cloud/camunda-cloud-8-1-element-type.spec.js, test/camunda-cloud/camunda-cloud-8-2-element-type.spec.js, test/camunda-cloud/integration/camunda-cloud-8-2-called-decision-or-task-definition.bpmn, test/camunda-cloud/integration/camunda-cloud-8-2-element-type-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-8-2-element-type.bpmn
This PR only covers modeling the elements, it does not add validation for the event itself. I created a follow-up issue for this: https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/62
\< 8.2
\>= 8.2
related to https://github.com/camunda/camunda-modeler/issues/3282
=> feat: allow link events in camunda 8.2

index.js, package-lock.json, package.json, rules/history-time-to-live.js, rules/utils/rule.js, test/camunda-platform/history-time-to-live.spec.js, test/camunda-platform/integration/history-time-to-live-errors.bpmn, test/camunda-platform/integration/history-time-to-live.bpmn, test/camunda-platform/integration/history-time-to-live.spec.js, test/config/configs.spec.js, test/helper.js
Related to https://github.com/camunda/camunda-modeler/issues/3369
Since we can't fully separate the rules in nested folders (because of `bpmnlint`), it's mixed in with the other rules. I also tried to accommodate for it (in tests and helpers) without making too many changes - feel free to propose a better structure
=> Add platform 'history time to live' required rule

rules/error-reference.js, test/camunda-cloud/error-reference.spec.js
Changes the rules regarding error events following https://github.com/camunda/camunda-modeler/issues/3362#issuecomment-1484057769.
---
Related to https://github.com/camunda/camunda-modeler/issues/3362
=> fix: disallow error references without error code

CHANGELOG.md, rules/error-reference.js, test/camunda-cloud/error-reference.spec.js
Missing `errorCode` wouldn't get reported due to early return. 🤦🏻‍♂️ `v1.0.1`, here we go! 🔥
=> fix: report missing `errorCode` in Camunda 8.2

index.js, rules/element-type/config.js, rules/no-expression.js, rules/signal-reference.js, test/camunda-cloud/camunda-cloud-1-0-element-type.spec.js, test/camunda-cloud/camunda-cloud-1-1-element-type.spec.js, test/camunda-cloud/camunda-cloud-1-2-element-type.spec.js, test/camunda-cloud/camunda-cloud-8-0-element-type.spec.js, test/camunda-cloud/camunda-cloud-8-1-element-type.spec.js, test/camunda-cloud/camunda-cloud-8-2-element-type.spec.js, test/camunda-cloud/camunda-cloud-8-3-element-type.spec.js, test/camunda-cloud/error-reference.spec.js, test/camunda-cloud/implementation.spec.js, test/camunda-cloud/integration/camunda-cloud-8-3-element-type-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-8-3-element-type.bpmn, test/camunda-cloud/integration/element-type.spec.js, test/camunda-cloud/integration/signal-reference-errors.bpmn, test/camunda-cloud/integration/signal-reference.bpmn, test/camunda-cloud/integration/signal-reference.spec.js, test/camunda-cloud/no-expression.spec.js, test/camunda-cloud/signal-reference.spec.js, test/config/configs.spec.js
* add Camunda 8.3 config
* adjust `element-type` configuration to support signal intermediaate throw and end events in Camunda 8.3
* add `signal-reference` rule to lint signal reference and name
---
Closes https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/93
=> Support Signal Intermediate Throw and End Event in Camunda 8.3

rules/timer/config.js, rules/timer/index.js, rules/utils/element.js, test/camunda-cloud/integration/camunda-cloud-1-0-timer-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-1-0-timer.bpmn, test/camunda-cloud/integration/camunda-cloud-1-1-timer-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-1-1-timer.bpmn, test/camunda-cloud/integration/camunda-cloud-1-2-timer-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-1-2-timer.bpmn, test/camunda-cloud/integration/camunda-cloud-1-3-timer-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-1-3-timer.bpmn, test/camunda-cloud/integration/camunda-cloud-8-0-timer-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-8-0-timer.bpmn, test/camunda-cloud/integration/camunda-cloud-8-1-timer-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-8-1-timer.bpmn, test/camunda-cloud/integration/camunda-cloud-8-2-timer-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-8-2-timer.bpmn, test/camunda-cloud/integration/camunda-cloud-8-3-timer-errors.bpmn, test/camunda-cloud/integration/camunda-cloud-8-3-timer.bpmn, test/camunda-cloud/integration/timer.spec.js, test/camunda-cloud/timer.spec.js, test/utils/element.spec.js
* 💚 supported by Zeebe 
* 💙 supported by Zeebe, cannot be modeled
* 🧡 supported by Zeebe 8.3 
* ❤️ not supported
Related to https://github.com/camunda/camunda-modeler/issues/3516
=> Support `bpmn:timeDate` for Timer Boundary and Intermediate Catch Events

index.js, test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3613
=> feat: support converging inclusive gateway in 8.3

CHANGELOG.md, index.js, test/config/configs.spec.js
This reverts commit 7ed5bb3d93abeb596232d42fb6d3c4244723933a. 
Related to https://github.com/camunda/camunda-modeler/issues/3747
=> feat: remove support for converging inclusive gateway in 8.3

index.js, rules/camunda-cloud/secrets.js, rules/utils/error-types.js, test/camunda-cloud/integration/secrets-errors.bpmn, test/camunda-cloud/integration/secrets.bpmn, test/camunda-cloud/integration/secrets.spec.js, test/camunda-cloud/secrets.spec.js, test/config/configs.spec.js
Added secrets rule.
required secrets format : `{{secrets.SECRET_WORD}}`
secrets can be in <zeebe:properties>, <zeebe:ioMapping> and in <zeebe:subscription>
result : 
```
Activity_0gcnr68  error  Element of type <zeebe:input> contains an invalid secret format in property 'body'. Must be {{secrets.YOUR_SECRET}}                               camunda-compat/secrets              
StartEvent_1      error  Element of type <zeebe:property> contains an invalid secret format in property 'activationCondition'. Must be {{secrets.YOUR_SECRET}}             camunda-compat/secrets              
Event_0hdo39k     error  Element of type <zeebe:property> contains an invalid secret format in property 'inbound.responseBodyExpression'. Must be {{secrets.YOUR_SECRET}}  camunda-compat/secrets …
```
=> feat(rule): add secrets rule

rules/camunda-cloud/link-event.js, test/camunda-cloud/link-event.spec.js
Turns out `getEventDefinition` returns the first event definition and doesn't filter by type. Should be fixed now. 😅
=> fix(link-event): fix check for link event definition

index.js, test/camunda-cloud/integration/secrets.spec.js, test/config/configs.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3834
=> feat(secrets): enable rule and report `warn`

rules/camunda-cloud/secrets.js, test/camunda-cloud/secrets.spec.js
Corrected secrets.js regex pattern;
Links to issue : https://camunda.slack.com/archives/C034N0E5YCX/p1696966815142039
=> Allow spaces and `-` in secret identifiers

package-lock.json, package.json, rules/camunda-cloud/feel.js
This PR integrates latest FEEL linter changes and restores the 1.1.0 Behavior of overriding the supplied error message. The Detailes message will be shown in the editor:
related to https://github.com/camunda/camunda-modeler/issues/3991
=> deps: integrate `@bpmn-io/feel-lint@1.2.0`

rules/camunda-cloud/no-loop.js, test/camunda-cloud/no-loop.spec.js
This uses [breadth-first search](https://en.wikipedia.org/wiki/Breadth-first_search), [cf. detailed rationale](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/165#issuecomment-2196882155). As a result it reduces the time needed for traversing the diagram from [SUPPORT-22488](https://jira.camunda.com/browse/SUPPORT-22488) from ~1 minute to 6ms. 
Related to https://github.com/camunda/camunda-modeler/issues/4401
Try it out with 
```
npx @bpmn-io/sr camunda/linting -l camunda/bpmnlint-plugin-camunda-compat#make-loop-detection-more-perfomant
```
=> chore(no-loop): use BFS to find loops

rules/camunda-cloud/no-loop.js
This is just a code-style change, related to the discussion here: https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/165#discussion_r1661077364
=> chore(no-loop): use `Array.from` instead of spread operator

CHANGELOG.md, rules/camunda-cloud/no-version-tag.js, test/camunda-cloud/no-version-tag.spec.js
Overlaps with `no-binding-type`. Since 8.6 supports all known binding types we can keep the code simple.
=> fix(no-version-tag): do not lint `zeebe:bindingType`

index.js, rules/camunda-cloud/no-version-tag.js, rules/camunda-cloud/version-tag.js, test/camunda-cloud/integration/no-version-tag-errors.bpmn, test/camunda-cloud/integration/no-version-tag.bpmn, test/camunda-cloud/integration/version-tag-errors.bpmn, test/camunda-cloud/integration/version-tag.bpmn, test/camunda-cloud/integration/version-tag.spec.js, test/camunda-cloud/no-version-tag.spec.js, test/camunda-cloud/version-tag.spec.js, test/config/configs.spec.js
* the `no-version-tag` rule will not lint the `zeebe:versionTag` attribute anymore, the scenario of binding by version tag with Camunda <8.6 is covered by the `no-binding-type` rule; as a result there will only be one lint error instead of two for what's essentially the same problem
* the new `version-tag` rule will lint version tags and report and report an error if they're empty
---
Related to https://github.com/camunda/camunda-modeler/issues/4519
Required by https://github.com/camunda/linting/pull/117
=> Fix version tag linting

CHANGELOG.md, rules/camunda-cloud/feel.js, test/camunda-cloud/feel.spec.js
`bpmn:Process` is not a `bpmn:FlowElement` and was therefore ignored.
Related to https://github.com/camunda/camunda-modeler/issues/4562
=> fix(feel): report errors for flow element containers

test/camunda-cloud/task-listener.spec.js
This is to confirm that the event type still works.
Related to https://github.com/camunda/camunda-modeler/issues/4748
=> test: verify new task listener event

package-lock.json, package.json, rules/camunda-cloud/element-type/config.js, test/camunda-cloud/camunda-cloud-8-3-element-type.spec.js, test/camunda-cloud/camunda-cloud-8-6-element-type.spec.js, test/camunda-cloud/camunda-cloud-8-7-element-type.spec.js
Support `bpmn:AdHocSubProcess` for Camunda 8.7 and newer. 
Related to https://github.com/camunda/camunda-modeler/issues/4739
=> feat: support ad-hoc subprocess

index.js, package-lock.json, package.json, rules/camunda-cloud/ad-hoc-sub-process-activity.js, test/camunda-cloud/ad-hoc-sub-process-activity.spec.js, test/camunda-cloud/feel.spec.js, test/camunda-cloud/integration/ad-hoc-sub-process-activity-errors.bpmn, test/camunda-cloud/integration/ad-hoc-sub-process-activity.bpmn, test/camunda-cloud/integration/ad-hoc-sub-process-activity.spec.js, test/config/configs.spec.js
Add a rule to ensure that an Ad-Hoc Sub-Process contains at least one activity.
Related to https://github.com/camunda/camunda-modeler/issues/4811
Bonus: bpmn dependencies bump.
=> Add `ad-hoc-sub-process-activity` rule + Housekeeping

package-lock.json, package.json, rules/camunda-cloud/called-element.js, rules/camunda-cloud/element-type/index.js, rules/camunda-cloud/error-reference.js, rules/camunda-cloud/escalation-reference.js, rules/camunda-cloud/feel.js, rules/camunda-cloud/message-reference.js, rules/camunda-cloud/zeebe-user-task.js, rules/camunda-platform/history-time-to-live.js, rules/helper.js
Follows up on https://github.com/bpmn-io/bpmnlint/pull/167 to add documentation URL to rules (where it exists). The URL will typically be part of the [Camunda Modeling Guidance](https://docs.camunda.io/docs/next/components/modeler/reference/modeling-guidance/) sites.
After this change is merged and integrated we can safely get rid of the `camunda/linting` URL logic, cf. https://github.com/camunda/linting/pull/129.
=> Add documentation URL to rules

rules/helper.js
Rules are stored not with `.md` suffix, but as a "folder", cf. [called-element](https://docs.camunda.io/docs/next/components/modeler/reference/modeling-guidance/rules/called-element/).
=> fix(rules): correct documentation URL location

rules/camunda-cloud/ad-hoc-sub-process.js, test/camunda-cloud/ad-hoc-sub-process.spec.js
The `completionCondition` expression and `cancelRemainingInstances` attribute will only be supported in Camunda 8.8+. This PR adds support to raise an error if one of these properties is set on a lower version.
- If the `cancelRemainingInstances` attribute is set (getting the value is not enough as it is defined to default to `true` in the BPMN spec, so there's always a value): raise an error if the version is < 8.8
- If an `<bpmn:completionCondition />` element exists: raise an error if the version is < 8.8
An example process XML containing both properties:
```xml
<bpmn:process id="Process_1" isExecutable="true">
<bpmn:adHocSubProcess id="Activity_186wn7x" cancelRemainingInstances="false">
<bpmn:task id="Activity_06d3rvb" name="A" />
<bpmn:task id="Activity_1bkr1i6" name="B" /> …
```
=> feat: add rules for ad-hoc subprocess completion configuration

CHANGELOG.md, rules/camunda-cloud/ad-hoc-sub-process.js, rules/camunda-cloud/error-reference.js, rules/camunda-cloud/execution-listener.js, rules/camunda-cloud/no-version-tag.js, rules/camunda-cloud/start-event-form.js, rules/camunda-cloud/task-listener.js, rules/camunda-cloud/user-task-form.js, rules/utils/error-types.js, test/camunda-cloud/ad-hoc-sub-process.spec.js
This fixes the validation for ad-hoc subprocess where it keeps reporting missing activity even when call activity is placed inside. We can and should use abstract type in this case.
Ad-hoc subprocess with a single call activity can be successfully deployed to 8.7.
=> fix: allow call activity in ad-hoc subprocess

rules/camunda-cloud/escalation-boundary-event-attached-to-ref.js, test/camunda-cloud/escalation-boundary-event-attached-to-ref.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/4859
Allow BoundaryEvent on ad-hoc subprocesses. Only Tasks are not allowed to have BoundaryEvents.
=> Allow boundaryEvent on ad-hoc subprocesses

rules/camunda-cloud/zeebe-user-task.js
Now moved to [*camunda naming](https://docs.camunda.io/docs/next/apis-tools/migration-manuals/migrate-to-camunda-user-tasks/).
Related to https://github.com/camunda/camunda-modeler/issues/4873
=> fix(camunda-cloud): correct zeebe-user-task documentation URL

rules/camunda-platform/history-time-to-live.js
Related to https://github.com/camunda/camunda-modeler/issues/4957
Because history time to live is the only camunda 7 rule with a doc reference I choose to hard code it directly. I don't think it is likely that we will add more documented camunda 7 rules.
```bash
npx @bpmn-io/sr camunda/linting -l camunda/bpmnlint-plugin-camunda-compat#4957-update-history-ttl-link -c 'npm run start:platform'
```
=> chore: update doc link for history ttl

CHANGELOG.md, rules/camunda-cloud/ad-hoc-sub-process.js, test/camunda-cloud/ad-hoc-sub-process.spec.js
Related to https://github.com/camunda/tmp-camunda-modeler-adhoc-subprocess/issues/3
Validation rules for output collection and output element:
=> feat: validate `outputCollection` and `outputElement` on `zeebe:adHoc`

CHANGELOG.md, rules/camunda-cloud/implementation/config.js, rules/camunda-cloud/implementation/index.js, test/camunda-cloud/implementation.spec.js, test/camunda-cloud/integration/no-priority-definition.spec.js
This PR adds a check for task definition in an ad-hoc subprocess. Since the element can have an implementation without a dedicated extension (`zeebe:AdHoc` can be present for both BPMN and job worker implementation), the logic needed to be adjusted.
Related to https://github.com/camunda/tmp-camunda-modeler-adhoc-subprocess/issues/1
Built on top of https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/212
=> Validate `bpmn:AdHocSubProcess` implementation
